server:
  servlet:
    context-path: /empsys

mybatis:
  type-aliases-package: com.lxq.springboot_emp.entity
  mapper-locations: classpath:mapper/*.xml

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/employee?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 2579
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      max-active: 20
      initial-size: 5
  thymeleaf:
    cache: false

    # 不显示thymeleaf日志
logging.level.org.thymeleaf:
  info
